import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { MAX_ORIGINAL_VIDEO_BYTES, MAX_VIDEO_IMPORTS_PER_BATCH, VIDEO_IMPORT_CONCURRENCY, formatVideoFileSize, mapWithConcurrency, VIDEO_STORAGE_BUCKET, VIDEO_COVER_BUCKET, MAX_COVER_IMAGE_BYTES, MAX_COVER_IMAGES_PER_BATCH, coverImageStoragePath, createCoverImageId, validateCoverImageFile } from '../src/uploaded-video-utils.js';
import { parseReelLines } from '../src/url-utils.js';

const libraryMigration = await readFile(new URL('../supabase/migrations/202610080005_uploaded_video_library.sql', import.meta.url), 'utf8');
const safetyMigration = await readFile(new URL('../supabase/migrations/202610080006_private_video_safety.sql', import.meta.url), 'utf8');
const importMigration = await readFile(new URL('../supabase/migrations/202610080007_instagram_url_archive_import.sql', import.meta.url), 'utf8');
const recoveryMigration = await readFile(new URL('../supabase/migrations/202610080008_recover_stale_video_imports.sql', import.meta.url), 'utf8');
const hardeningMigration = await readFile(new URL('../supabase/migrations/202610080009_private_url_import_hardening.sql', import.meta.url), 'utf8');
const coverQuotaMigration = await readFile(new URL('../supabase/migrations/202610080010_storage_quota_and_reel_covers.sql', import.meta.url), 'utf8');
const coverPolicyFixMigration = await readFile(new URL('../supabase/migrations/202610080011_fix_cover_storage_path_policy.sql', import.meta.url), 'utf8');
const perReelCoverMigration = await readFile(new URL('../supabase/migrations/202610080012_per_reel_cover_assignments.sql', import.meta.url), 'utf8');
const balancedRandomCoverMigration = await readFile(new URL('../supabase/migrations/202610080013_balanced_random_cover_selection.sql', import.meta.url), 'utf8');
const coverSelectionBackfillMigration = await readFile(new URL('../supabase/migrations/202610080014_backfill_cover_selection_counts.sql', import.meta.url), 'utf8');
const schema = await readFile(new URL('../supabase/schema.sql', import.meta.url), 'utf8');
const app = await readFile(new URL('../src/main.js', import.meta.url), 'utf8');
const worker = await readFile(new URL('../../reels_transfer/github_worker.py', import.meta.url), 'utf8');
const workflow = await readFile(new URL('../../.github/workflows/process-reels.yml', import.meta.url), 'utf8');
const workerTrigger = await readFile(new URL('../supabase/functions/publish-now-trigger/index.ts', import.meta.url), 'utf8');

 test('normalizes Instagram Reel URLs and keeps private archive size helpers', () => {
  assert.equal(MAX_ORIGINAL_VIDEO_BYTES, 50 * 1024 * 1024);
  assert.equal(VIDEO_STORAGE_BUCKET, 'reelflow-original-videos');
  assert.equal(MAX_VIDEO_IMPORTS_PER_BATCH, 20);
  assert.equal(VIDEO_IMPORT_CONCURRENCY, 5);
  assert.match(formatVideoFileSize(50 * 1024 * 1024), /50/);
  const parsed = parseReelLines('https://www.instagram.com/reel/ABC123/?igsh=one\nhttps://instagram.com/reels/abc123/\nhttps://instagram.com/reel/XYZ789/');
  assert.equal(parsed.items.length, 2);
  assert.equal(parsed.items[0].url, 'https://www.instagram.com/reel/ABC123/');
  assert.equal(parsed.duplicates, 1);
  assert.equal(parseReelLines('https://example.com/reel/ABC123').invalid.length, 1);
});

test('validates a private batch of JPEG cover images without changing the 20-Reel batch cap', () => {
  assert.equal(MAX_VIDEO_IMPORTS_PER_BATCH, 20);
  assert.equal(VIDEO_COVER_BUCKET, 'reelflow-cover-images');
  assert.equal(MAX_COVER_IMAGE_BYTES, 8 * 1024 * 1024);
  assert.equal(MAX_COVER_IMAGES_PER_BATCH, 20);
  assert.equal(validateCoverImageFile({ type: 'image/jpeg', size: 100 }), '');
  assert.match(validateCoverImageFile({ type: 'image/png', size: 100 }), /JPEG/);
  assert.match(validateCoverImageFile({ type: 'image/jpeg', size: MAX_COVER_IMAGE_BYTES + 1 }), /8 MB/);
  assert.equal(coverImageStoragePath('123e4567-e89b-42d3-a456-426614174000', '123e4567-e89b-42d3-a456-426614174001'), '123e4567-e89b-42d3-a456-426614174000/123e4567e89b42d3a456426614174001.jpg');
  assert.throws(() => coverImageStoragePath('someone-else', 'bad-id'), /geçersiz/);
  const fallbackId = createCoverImageId({ getRandomValues: (bytes) => { bytes.fill(1); return bytes; } });
  assert.match(fallbackId, /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
});

test('bulk URL queueing preserves order and caps concurrent requests', async () => {
  let active = 0;
  let maximumActive = 0;
  const result = await mapWithConcurrency(Array.from({ length: 20 }, (_, index) => index), VIDEO_IMPORT_CONCURRENCY, async (value) => {
    active += 1;
    maximumActive = Math.max(maximumActive, active);
    await new Promise((resolve) => setTimeout(resolve, 1));
    active -= 1;
    return value * 2;
  });
  assert.equal(maximumActive, VIDEO_IMPORT_CONCURRENCY);
  assert.deepEqual(result, Array.from({ length: 20 }, (_, index) => index * 2));
});

test('migrations keep originals private and add owner-isolated, retryable URL import jobs', () => {
  assert.match(libraryMigration, /'reelflow-original-videos'[\s\S]*false[\s\S]*52428800/);
  assert.match(libraryMigration, /CREATE TABLE IF NOT EXISTS public\.uploaded_videos/);
  assert.match(libraryMigration, /CREATE POLICY "ReelFlow users read their private originals"/);
  assert.match(libraryMigration, /CREATE OR REPLACE FUNCTION public\.enqueue_uploaded_video/);
  assert.match(safetyMigration, /worker_temporary_video_objects/);
  assert.match(safetyMigration, /CREATE POLICY "ReelFlow users replace only untracked originals"/);
  assert.match(importMigration, /CREATE TABLE IF NOT EXISTS public\.video_import_jobs/);
  assert.match(importMigration, /CREATE POLICY "ReelFlow users read their own video imports"/);
  assert.match(importMigration, /instagram\\\.com\/\(reel\|reels\|p\)/);
  assert.match(importMigration, /CREATE OR REPLACE FUNCTION public\.claim_video_import_job/);
  assert.match(importMigration, /FOR UPDATE SKIP LOCKED/);
  assert.match(importMigration, /CREATE OR REPLACE FUNCTION public\.finish_video_import/);
  assert.match(importMigration, /CREATE OR REPLACE FUNCTION public\.retry_video_import/);
  assert.match(importMigration, /GRANT EXECUTE ON FUNCTION public\.claim_video_import_job\(\) TO service_role/);
  assert.match(recoveryMigration, /45 minutes/);
  assert.match(recoveryMigration, /attempts >= 3/);
  assert.match(recoveryMigration, /status = 'processing'/);
  assert.match(hardeningMigration, /REVOKE INSERT ON public\.uploaded_videos FROM authenticated/);
  assert.match(hardeningMigration, /DROP POLICY IF EXISTS "ReelFlow users upload originals into their private folder"/);
  assert.match(hardeningMigration, /active_storage_path/);
  assert.match(hardeningMigration, /p_expected_user_id IS DISTINCT FROM v_user_id/);
  assert.match(hardeningMigration, /storage_object_still_exists/);
  assert.match(coverQuotaMigration, /CREATE OR REPLACE FUNCTION public\.reelflow_storage_usage/);
  assert.match(coverQuotaMigration, /FROM storage\.objects AS o/);
  assert.match(coverQuotaMigration, /'reelflow-cover-images'[\s\S]*false[\s\S]*8388608/);
  assert.match(coverQuotaMigration, /CREATE TABLE IF NOT EXISTS public\.video_cover_images/);
  assert.match(coverQuotaMigration, /CREATE POLICY "ReelFlow users read their own private Reel covers"/);
  assert.match(coverQuotaMigration, /enqueue_uploaded_video_with_cover/);
  assert.match(coverQuotaMigration, /claim_video_cover_cleanup/);
  assert.match(coverQuotaMigration, /finish_video_cover_cleanup/);
  assert.match(coverQuotaMigration, /cleanup_pending/);
  assert.match(coverQuotaMigration, /cover_image_id/);
  assert.match(coverPolicyFixMigration, /\[0-9a-f\]\{32\}\[\.\]jpg\$/);
  assert.match(perReelCoverMigration, /CREATE OR REPLACE FUNCTION public\.enqueue_reel_with_cover/);
  assert.match(perReelCoverMigration, /c\.user_id = v_user_id[\s\S]*FOR UPDATE/);
  assert.match(perReelCoverMigration, /GRANT EXECUTE ON FUNCTION public\.enqueue_reel_with_cover/);
  assert.match(balancedRandomCoverMigration, /ADD COLUMN IF NOT EXISTS selection_count bigint NOT NULL DEFAULT 0/);
  assert.match(balancedRandomCoverMigration, /pg_advisory_xact_lock[\s\S]*hashtextextended\(v_user_id::text, 0\)/);
  assert.match(balancedRandomCoverMigration, /ORDER BY c\.selection_count ASC, pg_catalog\.random\(\)/);
  assert.match(balancedRandomCoverMigration, /CREATE OR REPLACE FUNCTION public\.enqueue_reel_with_auto_cover/);
  assert.match(balancedRandomCoverMigration, /GRANT EXECUTE ON FUNCTION public\.enqueue_reel_with_auto_cover/);
  assert.match(coverSelectionBackfillMigration, /SELECT q\.cover_image_id, count\(\*\)::bigint AS selection_count/);
  assert.match(coverSelectionBackfillMigration, /history\.selection_count > c\.selection_count/);
  assert.match(schema, /CREATE TABLE IF NOT EXISTS public\.video_import_jobs/);
  assert.match(schema, /45 minutes/);
});

test('PWA queues URL-only archive imports and supports local bulk TXT lists', () => {
  assert.match(app, /id="video-library-section"/);
  assert.match(app, /İndirme durumu ve geçmiş/);
  assert.match(app, /data-import-filter="active"/);
  assert.match(app, /data-import-filter="ready"/);
  assert.match(app, /data-import-filter="failed"/);
  assert.match(app, /uploaded_video_id,created_at,updated_at,finished_at/);
  assert.match(app, /statusLabels = \{ queued: 'Sırada', processing: 'İndiriliyor', ready: 'Tamamlandı', failed: 'Hata', cancelled: 'İptal edildi' \}/);
  assert.match(app, /video-history-progress/);
  assert.match(app, /fmtHistoryDate/);
  assert.match(app, /id="video-import-form"/);
  assert.match(app, /id="video-import-urls"/);
  assert.match(app, /data-action="paste-video-import-urls"/);
  assert.match(app, /data-action="import-url-text-file"/);
  assert.match(app, /id="video-import-file" accept="\.txt,text\/plain"/);
  assert.match(app, /Tek seferde en fazla \$\{MAX_VIDEO_IMPORTS_PER_BATCH\}/);
  assert.match(app, /VIDEO_IMPORT_CONCURRENCY/);
  assert.match(app, /p_source_url: item\.url/);
  assert.match(app, /p_expected_user_id: userId/);
  assert.match(app, /video_import_id: addedImportIds\[0\]/);
  assert.match(app, /supabase\.functions\.invoke\('publish-now-trigger'/);
  assert.match(app, /authUserGeneration !== userGeneration/);
  assert.match(app, /state\.uploadedVideos\.some\(\(item\) => item\.id === videoId/);
  assert.match(app, /retry_video_import/);
  assert.match(app, /data-action="retry-video-import"/);
  assert.match(app, /data-video-account-select/);
  assert.match(app, /data-video-template-select/);
  assert.match(app, /data-action="preview-uploaded-video"/);
  assert.match(app, /data-action="queue-uploaded-video"/);
  assert.match(app, /createSignedUrl/);
  assert.match(app, /createSignedUrls/);
  assert.match(app, /reelflow_storage_usage/);
  assert.match(app, /Kalan \$\{formatStorageGigabytes\(left\)\} GB/);
  assert.match(app, /id="video-cover-files"[^>]*multiple/);
  assert.match(app, /data-video-cover-select/);
  assert.match(app, /Her Reel için hesap, açıklama ve kapak/);
  assert.match(app, /data-reel-cover-select data-shortcode-key=/);
  assert.match(app, /p_auto_select_cover: !state\.reelCoverImageSelections\[item\.shortcodeKey\]/);
  assert.match(app, /reelCoverImageSelections/);
  assert.match(app, /enqueue_uploaded_video_with_cover/);
  assert.match(app, /p_cover_image_id:/);
  assert.match(app, /refresh-storage-usage/);
  assert.doesNotMatch(app, /tus-js-client|video-upload-form/);
});

test('scheduled worker downloads accessible Instagram Reels into the private owner bucket', () => {
  assert.match(worker, /claim_video_import_job/);
  assert.match(worker, /_canonical_import_url/);
  assert.match(worker, /download_reel\(\s*canonical_url/);
  assert.match(worker, /upload_imported_video/);
  assert.match(worker, /finish_video_import/);
  assert.match(worker, /fail_video_import/);
  assert.match(worker, /reelflow-original-videos/);
  assert.match(worker, /signed_cover_image/);
  assert.match(worker, /reelflow-cover-images/);
  assert.match(worker, /cover_image_id/);
  assert.match(worker, /publish_kwargs\["cover_url"\]/);
  assert.match(workflow, /max_video_imports:[\s\S]*options: \['1', '3', '5'\]/);
  assert.match(workflow, /MAX_VIDEO_IMPORTS_PER_RUN:.*inputs\.max_video_imports \|\| '3'/);
  assert.match(workerTrigger, /video_import_id/);
  assert.match(workerTrigger, /from\("video_import_jobs"\)[\s\S]*eq\("user_id", user\.id\)/);
  assert.match(workerTrigger, /max_video_imports: "5"/);
});
